### ISSUE TITLE
invalid gemspec when using latest rubygems version

### ISSUE THREAD

**Issue by nfedyashev** [kristianmandrup/haversine#2]
Hi Kristian!

haversine started to throw warnings when I upgraded to the latest rubygems version
http://blog.rubygems.org/2011/08/25/1.8.10-released.html

    Invalid gemspec in [/Users/nikita/.rvm/gems/ruby-1.9.2-p180@chk2/specifications/haversine-0.3.0.gemspec]: invalid date format in specification: "2011-06-05 00:00:00.000000000Z"

**Comment by kristianmandrup** [comment]
http://stackoverflow.com/questions/7290575/invalid-date-format-specification-in-gemspec

`gem update --system`
