### ISSUE TITLE
distance calculate big error

### ISSUE THREAD

**Issue by mxyue** [kristianmandrup/haversine#6]
A:
log: 104.064254, lat: 30.643491,
B:
log: 104.070882, lat: 30.492061
A-B = 4158.631m
actually distance is  about 16869.1 m

**Comment by kristianmandrup** [comment]
Conversion of algorithm in javascript I think. I might have made a mistake. Look at comment in previous commit or look for haversine alg online. I never used this gem on its own in any real project. Sorry.

**Comment by mxyue** [comment]
I found my mistake,passed in error arguments,  Haversine.distance(longitude, latitude, longitude, latitude)
right: Haversine.distance(latitude, longitude,   latitude,longitude) 
above calculate distance is 16850.201 m,  Not that big error，I'm so sorry。

**Comment by kristianmandrup** [comment]
Good to hear :)
